{ config, lib, ... }:
{
	options.stylix.targets.custom.aerc.enable = lib.mkEnableOption "custom implementation of styling aerc";

	config.programs.aerc.stylesets.default = lib.mkIf config.stylix.targets.custom.aerc.enable ''
		*.selected.bold=true
		statusline_default.bold=true
		border.reverse=false
		part_mimetype.dim=false

		error.fg=1
		warning.fg=3
		success.fg=2
		title.fg=4
		title.bg=default
		statusline_default.fg=0
		statusline_default.bg=4
		statusline_error.bg=0
		statusline_warning.fg=3
		msglist_default.fg=7
		msglist_default.selected.fg=0
		msglist_default.selected.bg=7
		msglist_read.fg=7
		msglist_read.selected.fg=0
		msglist_read.selected.bg=7
		msglist_deleted.fg=1
		msglist_deleted.selected.fg=0
		msglist_deleted.selected.bg=1
		msglist_result.fg=2
		msglist_result.selected.fg=0
		msglist_result.selected.bg=2
		msglist_marked.fg=4
		msglist_marked.selected.fg=0
		msglist_marked.selected.bg=4
		msglist_flagged.fg=2
		msglist_flagged.selected.fg=0
		msglist_flagged.selected.bg=2
		msglist_unread.fg=5
		msglist_unread.selected.fg=0
		msglist_unread.selected.bg=5
		tab.fg=7
		tab.bg=8
		tab.selected.bg=4
		tab.selected.fg=0
		dirlist_default.selected.fg=0
		dirlist_default.selected.bg=7
		dirlist_unread.fg=5
		dirlist_unread.selected.fg=0
		dirlist_unread.selected.bg=5
		dirlist_recent.fg=4
		dirlist_recent.selected.fg=0
		dirlist_recent.selected.bg=4
		part_mimetype.fg=7
		part_mimetype.bg=8
		part_mimetype.selected.fg=0
		part_mimetype.selected.bg=4
		part_switcher.bg=8
		part_switcher.selected.bg=4
	'';
}
